# Creating MLflow deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-deployment
  template:
    metadata:
      labels:
        app: mlflow-deployment
    spec:
      containers:
      - name: mlflow-deployment
        image: pdemeulenaer/mlflow-server:537 #image-registry.openshift-image-registry.svc:5000/pdemeulenaer-dev/mlflow-on-kubernetes-image:latest #pdemeulenaer/mlflow-server:537 
        imagePullPolicy: IfNotPresent #Always
        args:
        - --host=0.0.0.0
        - --port=5000
        - --backend-store-uri=postgresql://mlflow_user:mlflow_pwd@10.107.203.184:5432/mlflow_db
        - --default-artifact-root=s3://mlflow/
        - --workers=2
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://10.109.86.100:9000/ #http://mlflow-minio.local:9000/
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin" #"minio"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minioadmin" #"minio123"
        # - name: MLFLOW_S3_IGNORE_TLS
        #   value: "true"
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        resources:
          requests:
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: mlflow-deployment
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mlflow-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.il/add-base-url: "true"
spec:
  rules:
  - host: mlflow-server.local
    http:
      paths:
        - backend:
            serviceName: mlflow-service
            servicePort: 5000
          path: /
